#!/usr/bin/env python

import os
import sys
import argparse
import subprocess
import struct

# Global variant
# genome: { 
#	chr_name: { 
#		seq: string,
#		order: integer,
#		gene_id: {
#			info: integer
#			transcript_id: [[exon_start, exon_end], ...]
#		}
#	}
# }

genome = {}
chromosome = []
nRed = 25
integer_size = 4

def get_argument():
	parser = argparse.ArgumentParser(usage='./hera_build  --fasta FASTA  --gtf GTF  --outdir OUTDIR\n[OPTIONAL]\n\t--full_index 0/1\n\t--grch38 0/1')
	parser._optionals.title = 'Arguments'
	parser.add_argument('--fasta', metavar='', help='input reference genome fasta file')
	parser.add_argument('--gtf', metavar='', help='input reference annotation gtf file')
	parser.add_argument('--outdir', metavar='', help='output directory')
	parser.add_argument('--full_index', metavar='', help='0: none, 1: index full genome')
	parser.add_argument('--grch38', metavar='', help='is input fasta GRCh38? 0: No, 1: Yes')

	return parser

# Load genome sequence from fasta file
# Extract order and chromosome name for bam header index
def load_genome(args):
	print("Scan reference sequence ...")

	# Total number of byte need to write/read index
	# First integer store number of chromosome
	total = integer_size

	with open(args.fasta, 'r') as f:
		name = seq = ''
		order = 0

		for line in f:
			if line[0] == '>':
				if name != '':
					total += len(name)
					genome[name] = {"seq" : seq, "order": order - 1}
					seq = ''
				name = line[1:-1].split(" ")[0]
				chromosome.append(name)
				order += 1
			else:
				seq += line[:-1]
				if args.grch38 == "1" and order >= nRed:
					break
		genome[name] = {"seq" : seq, "order" : order - 1}
		
		# 1 integer for name length
		# 1 integer for sequence length
		total += len(name) + 2 * integer_size * order
	return total

# Extract trascriptome information from gtf file
def extract_transcriptome(args):
	print ("Scan gtf file...")

	genes = []
	with open(args.gtf, 'r') as f:
		order = 0
		for line in f:
			if line[0] == '#':
				continue
			line = line[:-1].split('\t')

			key = line[8].replace(' \"', '\t').replace(' ', '').split('\";')
			if line[2] == 'gene':
				gene_inf = {}
				for k in key:
					k = k.split("\t")
					if k[0] == "gene_id" or k[0] == "gene_name":
						gene_inf[k[0]] = k[1]
				try:
					genome[line[0]][gene_inf["gene_id"]] = {"inf": order}
					genes.append(line[6] + gene_inf["gene_id"] + gene_inf["gene_name"])
					order += 1
				except:
					continue
			elif line[2] == 'transcript':
				transcript_inf = {}
				for k in key:
					k = k.split("\t")
					if k[0] == "gene_id" or k[0] == "transcript_id":
						transcript_inf[k[0]] = k[1]
				try:
					genome[line[0]][transcript_inf["gene_id"]][transcript_inf["transcript_id"]] = [] 
				except:
					continue
			elif line[2] == "exon":
				exon_inf = {}
				for k in key:
					k = k.split("\t")
					if k[0] == "gene_id" or k[0] == "transcript_id":
						exon_inf[k[0]] = k[1]
				try:
					genome[line[0]][exon_inf["gene_id"]][exon_inf["transcript_id"]].append( \
						[int(line[3]) - 1, int(line[4])])
				except:
					continue
	return genes

# Write index file
def write_index(total_byte, gene_info):
	print ("Extract transcript sequence")
	outdir = args.outdir

	if not os.path.exists(outdir):
		os.makedirs(outdir)

	# Store sequence of all transcript
	trans_file = open(os.path.join(outdir, "transcripts.fasta"), "w")
	# Store index for query
	inf_file = open(os.path.join(outdir, "reference.inf"), "wb")

	# BAM header [name length, name, sequence length]
	maxNameLen = 0
	inf_file.write(struct.pack("II", total_byte, len(chromosome)))
	for chr in chromosome:
		maxNameLen = max(maxNameLen, len(chr))
		inf_file.write(struct.pack("I", len(chr)))
		inf_file.write(chr.encode())
		inf_file.write(struct.pack("I", len(genome[chr]["seq"])))

	inf_file.write(struct.pack("II", len(chromosome), maxNameLen + 1))

	for chr in chromosome:
		inf_file.write(chr.encode())
		inf_file.write(('\0'*(maxNameLen - len(chr) + 1)).encode())
	for chr in chromosome:
		inf_file.write(struct.pack("I", len(genome[chr]["seq"])))

	# Gene name concated string
	maxNameLen = 0
	for gene in gene_info:
		maxNameLen = max(maxNameLen, len(gene))

	inf_file.write(struct.pack("II", len(gene_info), maxNameLen + 1))
	for gene in gene_info:
		inf_file.write(gene.encode())
		inf_file.write(('\0'*(maxNameLen - len(gene) + 1)).encode())

	# Consecutively write transcript info for each gene
	# [number of exon, [consecutive exon start], [consecutive exon end]]
	for chr in genome:
		for gene in genome[chr]:
			if gene == "seq" or gene == "order":
				continue
			for transcript in genome[chr][gene]:
				if transcript == "inf":
					continue
				trans_file.write(">%s:%s\n" % (transcript, gene))
				genome[chr][gene][transcript] = sorted(genome[chr][gene][transcript])
				inf_file.write(struct.pack("I", len(genome[chr][gene][transcript])))
				for pos in genome[chr][gene][transcript]:
					inf_file.write(struct.pack("I", pos[0]))
					trans_file.write("%s" % (genome[chr]["seq"][pos[0]:pos[1]]))
				for pos in genome[chr][gene][transcript]:
					inf_file.write(struct.pack("I", pos[1] - 1))
				trans_file.write("\n")

	# Write chromosome that a transcript belong to in form of index order
	for chr in genome:
		for gene in genome[chr]:
			if gene == "seq" or gene == "order":
				continue
			for transcript in genome[chr][gene]:
				if transcript == "inf":
					continue
				inf_file.write(struct.pack("I", genome[chr]["order"]))

	# Write gene that a transcript belong to in form of index order
	for chr in genome:
		for gene in genome[chr]:
			if gene == "seq" or gene == "order":
				continue
			for transcript in genome[chr][gene]:
				if transcript == "inf":                                                     
					continue
				inf_file.write(struct.pack("I", genome[chr][gene]["inf"]))

	trans_file.close()
	inf_file.close()

argument = get_argument()
args = argument.parse_args()

# Detect missing argument
if str(args.fasta) == "None":
	argument.print_help()
	sys.exit(0)

if str(args.gtf) == "None":
	argument.print_help()
	sys.exit(0)

if str(args.outdir) == "None":
	argument.print_help()
	sys.exit(0)

if str(args.grch38) == "None":
	args.grch38 = "0"

total_byte = load_genome(args)
gene_info = extract_transcriptome(args)
write_index(total_byte, gene_info)

# Call Hera index
path = sys.argv[0].replace("hera_build", "hera")
full = args.full_index

if str(full) == "None":
	subprocess.call([path , "index", "-t", os.path.join(args.outdir, "transcripts.fasta"), "-o", os.path.join(args.outdir, "index")])
else:
	subprocess.call([path , "index", "-t", os.path.join(args.outdir, "transcripts.fasta"), "-o", os.path.join(args.outdir, "index"), "-g", args.fasta])
